mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fashionist.fashion-urls')),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fashionist/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

#Model zum Erstellen der Blog-Beiträge auf der Startseite
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    picture=models.CharField(max_length=500, blank=True)
    link=models.CharField(max_length=500, default='', blank=True)
    image = models.ImageField(upload_to='images/')
    CATEGORY_CHOICES=[
        ('HS','Hairstyle'),
        ('MU','Make-Up'),
        ('SH','Shoes'),
        ('AC','Accessoirs'),
        ('OD','Outfit of the Day'),
        ('EE','Everything Else')
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='EE',
    )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

#Model zum Erstellen eines Beitrags über die Nutzerin
class About_Me(models.Model):
    image=models.ImageField(upload_to='images/', blank=True)
    about_me=models.TextField(default='')

#Model zum Erstellen von Event-Beiträge
class Events(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    event_date=models.DateField()
    event_time=models.TimeField()
    location=models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='images/', blank=True)

fashionist/forms.py
from django import forms
from .models import Post, About_Me, Events

class PostForm(forms.ModelForm):

    class Meta:
        model = Post 
        fields = ('title', 'text','category', 'image', 'link')

class InfoForm(forms.ModelForm):

    class Meta:
        model = About_Me
        fields = ('image','about_me')

class EventsForm(forms.ModelForm):

    class Meta:
        model = Events
        fields = ('title', 'text','event_date','event_time', 'location' ,'image')
        labels = {
            "event_date": "Date of the Event (dd.mm.yyyy)",
            "event_time": "Time of the Event (hh:mm)"
        }


         

fashionist/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post, About_Me, Events
from django.shortcuts import render, get_object_or_404
from .forms import PostForm, InfoForm, EventsForm
from django.shortcuts import redirect


#Neuen Beitrag erstellen
def new_news(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('news_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'fashionist/news_edit.html', {'form': form})

#Detailansicht des Beitrags
def news_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'fashionist/news_detail.html', {'post': post})

#Beitrag bearbeiten
def news_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST,    request.FILES,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('news_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'fashionist/news_edit.html', {'form': form})


#Startseite - Übersicht über Blogeinträge
def frontpage(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    query=request.GET.get("q")
    if query:
        posts=posts.filter(category=query)
    return render(request, 'fashionist/frontpage.html', {'posts': posts})

#Seite zur Nutzerin des Blogs, Bild und Text können hier hochgeladen werden
#Erstellter Objekt des Models About_Me wird immer mit pk=1 gespeichert, da es nur eine Nutzerin gibt
def about_me(request):
    if not About_Me.objects.filter(pk=1).exists():
        if request.method == "POST":
            form = InfoForm(request.POST, request.FILES)
            if form.is_valid():
                info = form.save(commit=False)
                info.pk=1
                info.save()
                return redirect('about_me')
        else:
            form = InfoForm()
        return render(request, 'fashionist/edit_info.html', {'form': form})
    else:
        info=About_Me.objects.get(pk=1)
        return render(request, 'fashionist/about_me.html', {'info': info})

#About_Me bearbeiten
def edit_info(request):
        info = get_object_or_404(About_Me, pk=1)
        if request.method == "POST":
            form = InfoForm(request.POST, request.FILES, instance=info)
            if form.is_valid():
                info = form.save(commit=False)
                info.save()
                return redirect('about_me')
        else:
            form = InfoForm(instance=info)
        return render(request, 'fashionist/edit_info.html', {'form': form})

#Eventpage
def events(request):
    events = Events.objects.filter(event_date__gte=timezone.now()).order_by('event_date')
    return render(request, 'fashionist/events.html', {'events': events})

#Event erstellen
def new_events(request):
    if request.method == "POST":
        form = EventsForm(request.POST, request.FILES)
        if form.is_valid():
            events = form.save(commit=False)
            events.author = request.user
            events.save()
            return redirect('events')
    else:
        form = EventsForm()
    return render(request, 'fashionist/events_edit.html', {'form': form})

#Event bearbeiten
def events_edit(request, pk):
    event = get_object_or_404(Events, pk=pk)
    if request.method == "POST":
        form = EventsForm(request.POST, request.FILES,instance=event)
        if form.is_valid():
            events = form.save(commit=False)
            events.author = request.user
            events.save()
            return redirect('events')
    else:
        form = EventsForm(instance=event)
    return render(request, 'fashionist/events_edit.html', {'form': form})

fashionist/templates/fashionist/about_me.html
{% extends 'fashionist/base.html' %}

{% block content %}
    <div class="col-md-4"></div>
    <div class="col-md-4">
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'edit_info' %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        {% if info.image %}
            <p><img src="{{info.image.url}}" class="img-responsive" alt="Die Bild-Adresse oder der Pfad ist nicht korrekt" /></p>
        {% endif %}
        <br>
        <br>

        <h2>About myself:</h2> <p>{{info.about_me}}</p>
    </div>
{% endblock %}

fashionist/templates/fashionist/base.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Fashionist</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <!--Schriftarten-->
        <link href="https://fonts.googleapis.com/css?family=Parisienne|Yellowtail&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Great+Vibes&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Yeseva+One&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto|Yeseva+One&display=swap" rel="stylesheet">
        
        
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'main/gijgo.min.css' %}">

        <link rel="stylesheet" href="{% static 'css/fashionist.css' %}">
        
    


    </head>
    <body>
            <!--Navigationsleiste Bootstrap-->
            <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">

                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span> 
                        </button>
                    </div>

                    <div class="navbar-collapse collapse" id="myNavbar">
                            <ul class="nav navbar-nav">
                                <li><a href="/">Trends</a></li>
                                <li><a href="/">Guide</a></li>
                                <li><a href="/">Lifestyle</a></li>
                                <li><a href="/events/">Events</a></li>
                                <li><a href="/about_me/">About Me</a></li>
                            </ul>

                    </div>
                </div> 
        <div class="seite">
           
                
                {% if user.is_authenticated %}
                    <a href="{% url 'new_news' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> 
                {% endif %}                 

            


            <div class="page-header">
                <h1 style='text-align:center;'><a href="/"><img src="https://i.ibb.co/kH6vQPC/Bildschirmfoto-2019-07-02-um-20-51-03.png" id="logo" alt="Bildschirmfoto-2019-07-02-um-20-51-03" height="150" width="200"></a></h1>

                    
                
            </div>

            
            
            

        <div class="container">
            <div class="row">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
        <br>
        </div>
        <footer class="footer-class">
            <div class="second-last-balken">
                <br>
                <br>
            </div>
            <div class="last-balken">
                <br>
                <br>
                <h1 class="last-bar" text-align="center"><a href="#top" class="to-top">Livia's Life</a></h1>
                <br>
                <br>
            </div> 
        </footer>
        <script src="{% static 'main/gijgo.min.js' %}" charset="utf-8"></script>
        <script type="text/javascript">$('#id_event_date').datepicker({ format: 'dd.mm.yyyy' }  );</script>
    </body>
</html>
<!-- Fertig? -->
<!-- Stand 02.07.19-->

fashionist/templates/fashionist/edit_info.html
{% extends 'fashionist/base.html' %}

{% block content %}
    <div class="col-md-2"></div>
    <div class="col-md-8"> 
        <div class="about_me_title">
            <a href="/about_me/" ><h1>About Me</h1></a> 
        </div>
        
        <form method="POST" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </div>
    
{% endblock %}

fashionist/templates/fashionist/events.html
{% extends 'fashionist/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        {% if user.is_authenticated %}
            <a href="{% url 'new_events' %}" class="new-event"><span class="badge badge-secondary">New</span></a> 
        {% endif %} 
        <div class="col-md-10"></div>
    </div>
        
    {% for event in events %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="events">
                
                <br>
                {% if user.is_authenticated %}
                    <a class="btn btn-default" href="{% url 'events_edit' pk=event.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                {% endif %}
                <h1>{{ event.title }}</h1>
                {% if event.image %}
                <p><img src="{{event.image.url}}" class="img-responsive" alt="Die Bild-Adresse oder der Pfad ist nicht korrekt"/></p>
                {% endif %}

                <div class="date-event">
                    {{ event.event_date }}
                </div>
                <div class="time">
                    {{ event.event_time }}
                </div>
                {% if event.location %}
                <div class="location">
                    {{event.location}}
                </div>
                {% endif %}
                <div class="text">
                    <p>{{ event.text|linebreaksbr }}</p>
                </div>
                
                
                
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
    {% endfor %}
{% endblock %}

fashionist/templates/fashionist/events_edit.html
{% extends 'fashionist/base.html' %}

{% block content %}
    <div class="col-md-2"></div>
    <div class="col-md-8"> 
        <h2>Event</h2>
        <form method="POST" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
        
    </div>
    
{% endblock %}

fashionist/templates/fashionist/frontpage.html
{% extends 'fashionist/base.html' %}


{% block content %}
    <div class="startpage-img">
        <img src="https://www.bilder-upload.eu/upload/1a0549-1562238620.jpg"  class="img-responsive" id="startpage-img" alt="" >
    </div>
    <div class="search">
        <form action="" method="get">
            <label class="label-for-sel" for="sel">Categories</label>
            <select name="q" id="sel">
                <option value=""></option>
                <option value="HS">Hairstyle</option>
                <option value="MU">Make-Up</option>
                <option value="SH">Shoes</option>
                <option value="AC">Accessoires</option>
                <option value="OD">Outfit of the Day</option>
                <option value="EE">Everything Else</option>
            </select>
            <input type="submit" value="Search">
            
        </form>
    </div>
    {% for post in posts %}
    <div class="col-md-12">
        <div class="row">
            <div class="post">
                <div class="col-sm-6">
                    <div class="col-lg-3 col-sm-1 "></div>
                    <div class="col-lg-9 col-sm-11">
                        <br>
                        <br>
                        {% if post.image %}
                            <p><a href="{% url 'news_detail' pk=post.pk %}" id="id_frontpage_image"><img src="{{post.image.url}}" class="img-responsive" alt="Die Bild-Adresse oder der Pfad ist nicht korrekt" /></a></p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4 col-sm-5">
                    <br>
                    <h1><a href="{% url 'news_detail' pk=post.pk %}" class="post-title">{{ post.title }}</a></h1>
                    <div class="date">
                        {{ post.published_date }}
                    </div>
                    <div class="text">
                        <p>{{ post.text|linebreaksbr|truncatechars:350 }}</p>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-1"></div>
            </div>
        </div>    
    </div>
    {% endfor %}
{% endblock %}

fashionist/templates/fashionist/news_detail.html
{% extends 'fashionist/base.html' %}

{% block content %}
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="post">
            
            {% if user.is_authenticated %}
                <a class="btn btn-default" href="{% url 'news_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            {% endif %}

            <h2>{{ post.title }}</h2>
            {% if post.published_date %}
                <div class="date">
                    {{ post.published_date }}
                </div>
            {% endif %}
            {% if post.image %}
                <p><img src="{{post.image.url}}" class="img-responsive" alt="" ></p>
            {% endif %}
            <p>{{ post.text|linebreaksbr }}</p>
            <br><br>
            <p>Link zu diesem Thema:</p>
            <p><a href="{{post.link}}">{{post.link}}</a></p>
        </div>
    </div>

{% endblock %}

fashionist/templates/fashionist/news_edit.html
{% extends 'fashionist/base.html' %}

{% block content %}
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h2>New post</h2>
        <form method="POST" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </div>
{% endblock %}

fashionist/templates/fashionist/trends.html
{% extends 'fashionist/base.html' %}


{% block content %}
    {% for post in posts %}
    <div class="col-md-12">
        <div class="row">
            <div class="post">
                <div class="col-sm-6">
                    <div class="col-lg-3 col-sm-1 "></div>
                    <div class="col-lg-9 col-sm-11">
                        <br>
                        <br>
                        {% if post.image %}
                            <p><img src="{{post.image.url}}" class="img-responsive" alt="Die Bild-Adresse oder der Pfad ist nicht korrekt"/></p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4 col-sm-5">
                    <br>
                    <h1><a href="{% url 'news_detail' pk=post.pk %}" class="post-title">{{ post.title }}</a></h1>
                    <div class="date">
                        {{ post.published_date }}
                    </div>
                    <div class="text">
                        <p>{{ post.text|linebreaksbr|truncatechars:350 }}</p>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-1"></div>
            </div>
        </div>    
    </div>
    {% endfor %}
{% endblock %}

<!--
{% load static %}
<html>
    <head>
        <title>Fashionist</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/fashionist.css' %}">

    </head>
    <body>
            <div class="page-header">
                {% if user.is_authenticated %}
                    <a href="{% url 'new_news' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a> 
                {% endif %}
                <h1 style='text-align:center;'><a href="/"><img src="https://i.ibb.co/qrpyPdP/d2db7109-e68a-4c8a-8a0c-bc6c6315c8d9-200x200.png" alt=""  height="100" width="100">&nbsp;&nbsp;Livias Life</a></h1>
                <div class="categories" style='text-align:center;'>
                    <p style='text-align:center;'>Neues &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    Guide &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Lifestyle &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="/about_me/">Über mich</a></p>            
                </div>
            </div>
        </div>
        <div class="content container">
            <div class="main">
            {% for post in posts %}
                <div class="post">
                    <div class="row">
                        {% if isEvenNumber %}
                            <div class="col-md-2"></div>
                            <div class="col-md-6">
                                <p><img src="{{post.picture}}" alt="" height="333" width="500"></p>
                            </div>
                            <div class="col-md-4">
                                <h1><a href="{% url 'news_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                                <div class="date">
                                    {{ post.published_date }}
                                </div>
                                <p>{{ post.text|linebreaksbr }}</p>
                                <p><a href="{{post.link}}">{{post.link}}</a></p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>

        </div>
    </body>
</html>

-->